package com.stool.jetpackstechreborn.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.LongFieldControllerBuilder;
import dev.isxander.yacl3.config.v2.api.ConfigClassHandler;
import dev.isxander.yacl3.config.v2.api.serializer.GsonConfigSerializerBuilder;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;

import java.nio.file.Path;

public class JetpackConfigHandler {
    private static final ConfigClassHandler<JetpackConfig> HANDLER = ConfigClassHandler.createBuilder(JetpackConfig.class)
            .id(Identifier.fromNamespaceAndPath("jetpacks", "config"))
            .serializer(config -> GsonConfigSerializerBuilder.create(config)
                    .setPath(FabricLoader.getInstance().getConfigDir().resolve("jetpacks.json"))
                    .setJson5(true)
                    .build())
            .build();

    public static void load() {
        HANDLER.load();
    }

    public static JetpackConfig getConfig() {
        return HANDLER.instance();
    }

    public static Screen createConfigScreen(Screen parent) {
        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("jetpacks.config.title"))
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("jetpacks.config.category.general"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("jetpacks.config.group.simple"))
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.capacity"))
                                        .binding(HANDLER.defaults().simpleCapacity, () -> HANDLER.instance().simpleCapacity, val -> HANDLER.instance().simpleCapacity = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.thrust"))
                                        .binding(HANDLER.defaults().simpleThrust, () -> HANDLER.instance().simpleThrust, val -> HANDLER.instance().simpleThrust = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L).max(100L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.energy_cost"))
                                        .binding(HANDLER.defaults().simpleEnergyCost, () -> HANDLER.instance().simpleEnergyCost, val -> HANDLER.instance().simpleEnergyCost = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.hover_cost"))
                                        .binding(HANDLER.defaults().simpleHoverCost, () -> HANDLER.instance().simpleHoverCost, val -> HANDLER.instance().simpleHoverCost = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("jetpacks.config.group.advanced"))
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.capacity"))
                                        .binding(HANDLER.defaults().advancedCapacity, () -> HANDLER.instance().advancedCapacity, val -> HANDLER.instance().advancedCapacity = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.thrust"))
                                        .binding(HANDLER.defaults().advancedThrust, () -> HANDLER.instance().advancedThrust, val -> HANDLER.instance().advancedThrust = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L).max(100L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.energy_cost"))
                                        .binding(HANDLER.defaults().advancedEnergyCost, () -> HANDLER.instance().advancedEnergyCost, val -> HANDLER.instance().advancedEnergyCost = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.hover_cost"))
                                        .binding(HANDLER.defaults().advancedHoverCost, () -> HANDLER.instance().advancedHoverCost, val -> HANDLER.instance().advancedHoverCost = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("jetpacks.config.group.industrial"))
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.capacity"))
                                        .binding(HANDLER.defaults().industrialCapacity, () -> HANDLER.instance().industrialCapacity, val -> HANDLER.instance().industrialCapacity = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.thrust"))
                                        .binding(HANDLER.defaults().industrialThrust, () -> HANDLER.instance().industrialThrust, val -> HANDLER.instance().industrialThrust = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L).max(100L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.energy_cost"))
                                        .binding(HANDLER.defaults().industrialEnergyCost, () -> HANDLER.instance().industrialEnergyCost, val -> HANDLER.instance().industrialEnergyCost = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.hover_cost"))
                                        .binding(HANDLER.defaults().industrialHoverCost, () -> HANDLER.instance().industrialHoverCost, val -> HANDLER.instance().industrialHoverCost = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("jetpacks.config.group.ultimate"))
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.capacity"))
                                        .binding(HANDLER.defaults().ultimateCapacity, () -> HANDLER.instance().ultimateCapacity, val -> HANDLER.instance().ultimateCapacity = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.thrust"))
                                        .binding(HANDLER.defaults().ultimateThrust, () -> HANDLER.instance().ultimateThrust, val -> HANDLER.instance().ultimateThrust = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L).max(100L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.energy_cost"))
                                        .binding(HANDLER.defaults().ultimateEnergyCost, () -> HANDLER.instance().ultimateEnergyCost, val -> HANDLER.instance().ultimateEnergyCost = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .option(Option.<Long>createBuilder()
                                        .name(Component.translatable("jetpacks.config.option.hover_cost"))
                                        .binding(HANDLER.defaults().ultimateHoverCost, () -> HANDLER.instance().ultimateHoverCost, val -> HANDLER.instance().ultimateHoverCost = val)
                                        .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L))
                                        .build())
                                .build())
                        .option(Option.<Long>createBuilder()
                                .name(Component.translatable("jetpacks.config.option.hover_descent"))
                                .binding(HANDLER.defaults().hoverDescent, () -> HANDLER.instance().hoverDescent, val -> HANDLER.instance().hoverDescent = val)
                                .controller(opt -> LongFieldControllerBuilder.create(opt).min(0L).max(100L))
                                .build())
                        .option(Option.<Long>createBuilder()
                                .name(Component.translatable("jetpacks.config.option.hover_activation_velocity"))
                                .binding(HANDLER.defaults().hoverActivationVelocity, () -> HANDLER.instance().hoverActivationVelocity, val -> HANDLER.instance().hoverActivationVelocity = val)
                                .controller(opt -> LongFieldControllerBuilder.create(opt).min(-100L).max(100L))
                                .build())
                        .option(Option.<Long>createBuilder()
                                .name(Component.translatable("jetpacks.config.option.boost_speed"))
                                .binding(HANDLER.defaults().boostSpeedMultiplier, () -> HANDLER.instance().boostSpeedMultiplier, val -> HANDLER.instance().boostSpeedMultiplier = val)
                                .controller(opt -> LongFieldControllerBuilder.create(opt).min(100L).max(1000L))
                                .build())
                        .option(Option.<Long>createBuilder()
                                .name(Component.translatable("jetpacks.config.option.boost_energy"))
                                .binding(HANDLER.defaults().boostEnergyMultiplier, () -> HANDLER.instance().boostEnergyMultiplier, val -> HANDLER.instance().boostEnergyMultiplier = val)
                                .controller(opt -> LongFieldControllerBuilder.create(opt).min(100L).max(2000L))
                                .build())
                        .build())
                .save(HANDLER::save)
                .build()
                .generateScreen(parent);
    }
}
